import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const trace = fs.readFileSync(path.join(here, '..', 'src/core/operator-trace.js'), 'utf8');
const rail = fs.readFileSync(path.join(here, '..', 'src/ui/rail.js'), 'utf8');
const guide = fs.readFileSync(path.join(here, '..', 'src/ui/guide.js'), 'utf8');
const lifecycle = fs.readFileSync(path.join(here, '..', 'src/core/action-lifecycle.js'), 'utf8');
assert.match(trace, /TRACE_STORAGE_KEY = 'simnet_workbench_trace_v2'/);
assert.match(trace, /TRACE_MAX_EVENTS = 3000/);
assert.match(trace, /TRACE_MAX_BYTES = 1200000/);
assert.match(trace, /TRACE_QUEUE_MAX = 600/);
assert.match(trace, /pendingDroppedEventsCount/);
assert.match(trace, /function startUiObserver\(\)/);
assert.match(trace, /attributeFilter: \['class','style','hidden','aria-expanded','aria-hidden'\]/);
assert.match(trace, /attributeOldValue: true/);
assert.match(trace, /recentNativeUiMutationTarget/);
assert.match(trace, /correlatedToRecentOperatorAction/);
assert.match(trace, /visualState/);
assert.match(trace, /recordSystemEvent/);
assert.match(guide, /FOCUS_SHOW/);
assert.match(lifecycle, /ACTION_STATE/);
assert.doesNotMatch(trace, /operator_hover/);
assert.doesNotMatch(trace, /mousemove/);
assert.match(trace, /stopAndExport/);
assert.match(trace, /simnet-workbench-trace-export-v2/);
assert.match(rail, /Остановить и экспортировать/);
assert.match(rail, /data-action="operator-trace-export"/);
console.log('trace_recorder_v2_contract_test: PASS');
