import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const guide = fs.readFileSync(path.join(here, '..', 'src/ui/guide.js'), 'utf8');
const rail = fs.readFileSync(path.join(here, '..', 'src/ui/rail.js'), 'utf8');
const background = fs.readFileSync(path.join(here, '..', 'src/background.js'), 'utf8');
const lifecycle = fs.readFileSync(path.join(here, '..', 'src/core/action-lifecycle.js'), 'utf8');

assert.match(lifecycle, /REQUESTED:[\s\S]*NAVIGATING/);
assert.match(lifecycle, /SHOWN:[\s\S]*COMPLETED/);
assert.match(lifecycle, /ACTION_FOCUS_DROPPED_UNEXPECTEDLY/);
assert.match(lifecycle, /ACTION_ILLEGAL_STATE_TRANSITION/);
assert.match(lifecycle, /ACTION_TARGET_REBIND_FAILED/);
assert.match(lifecycle, /armInterruptionGuard/);
assert.match(lifecycle, /USER_INTERRUPTED/);
assert.match(lifecycle, /Critical invariant: SHOWN has no TTL/);
assert.match(lifecycle, /registerResolver/);
assert.match(lifecycle, /async function flushPersistence/);
assert.match(guide, /registerResolver\?\.\('userside\.tmc'/);
assert.match(guide, /registerResolver\?\.\('billing\.poll\.entry'/);
assert.match(guide, /tryRebindTarget\(\)/);
assert.match(guide, /this\.clear\('BACKDROP_CLICK'\)/);
assert.match(guide, /this\.clear\('ESC'\)/);
assert.match(guide, /this\.clear\('TARGET_ACTIVATED'\)/);
assert.match(rail, /async requestPollReveal\(\)[\s\S]*semanticTargetId: 'billing\.olt\.request'[\s\S]*destinationPageKind: 'billing_onu_poll'/, 'poll one-shot uses universal lifecycle directly to the real native askOLT destination');
assert.match(rail, /startGuidedLifecycle\('tmc'/);
assert.match(rail, /startGuidedLifecycle\(key,[\s\S]*replayOnly: true/);
assert.doesNotMatch(rail, /oneShotFocusTarget/);
assert.doesNotMatch(rail, /evidenceReplayTarget/);
assert.doesNotMatch(rail, /pollRevealPending/);
assert.match(background, /namespace === 'actionSession'/);

const railNavStart = rail.indexOf("WB.actionLifecycle?.navigationStarted?.(session, { actualResult: destination.destinationPageKind");
const railPersist = rail.indexOf("await WB.actionLifecycle?.flushPersistence?.();", railNavStart);
const railActualNav = rail.indexOf("if (key === 'technical') result", railPersist);
assert.ok(railNavStart >= 0 && railPersist > railNavStart && railActualNav > railPersist, 'one-shot cross-page action persists before native navigation');
const guidePersistHelper = guide.indexOf('const persistNavigationIntent = async actualResult =>');
const guideNavStart = guide.indexOf('WB.actionLifecycle?.navigationStarted?.(actionSession, { actualResult });', guidePersistHelper);
const guidePersist = guide.indexOf('return WB.actionLifecycle?.flushPersistence?.();', guideNavStart);
const guideTargetPersist = guide.indexOf('await persistNavigationIntent(targetUrl);', guidePersist);
const guideLocation = guide.indexOf('location.assign(targetUrl)', guideTargetPersist);
assert.ok(guidePersistHelper >= 0 && guideNavStart > guidePersistHelper && guidePersist > guideNavStart && guideTargetPersist > guidePersist && guideLocation > guideTargetPersist, 'Guide flushes one coalesced NAVIGATING ActionSession before same-tab navigation');
const showStart = guide.indexOf('async show(currentPlan');
const showEnd = guide.indexOf('railLeftBoundary()', showStart);
const showBody = guide.slice(showStart, showEnd);
assert.doesNotMatch(showBody, /await markPlanHint\(/, 'Focus rendering never waits behind the full Case persistence queue');
console.log('universal_action_guide_contract_test: PASS');
